name: Build and Deploy to Bluehost

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [wordpress-update]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create environment file
      run: |
        echo "NEXT_PUBLIC_WORDPRESS_API_URL=${{ secrets.NEXT_PUBLIC_WORDPRESS_API_URL }}" > .env.local
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local
        echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.local

    - name: Build application
      run: npm run build

    - name: Deploy to Bluehost via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_path: './out/*'
        remote_path: ${{ secrets.FTP_SERVER_DIR }}
        sftp_only: true

    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "Site updated at: ${{ secrets.NEXTAUTH_URL }}" 